services:
  database:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD:  ${CONFIG_MARIADB_ADMINPASSWORD}
      MARIADB_DATABASE: ${CONFIG_MARIADB_DATABASE}
      MARIADB_USER: ${CONFIG_MARIADB_ADMINUSERNAME}
      MARIADB_PASSWORD: ${CONFIG_MARIADB_ADMINPASSWORD}
    ports:
     - "3306:3306"
    networks:
      - fastapi_network
    volumes:
    # to have persistent database we need to uncomment the next line.
    #  - mariadb_volume:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  web:
    container_name: chatbot
    build: ../webserver/.
    ports:
      - "8000:8000"
    networks:
      - fastapi_network
    depends_on:
      - database
    volumes:
      - ../webserver:/app


  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAM_KEEP_ALIVE=1h ollama serve
    networks:
      - fastapi_network
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
volumes:
  ollama:
  # to have persistent database we need to uncomment the next line.
  #mariadb_volume:

networks:
  fastapi_network:
    name: fastapi_network
    driver: bridge